### ISSUE TITLE
Configure fails due to format of test statement

### ISSUE THREAD

**Issue by JustScreaming** [ANTsX/ITKR#66]
I am trying to compile an apptainer using debian:bullseye-slim.  The addition of this statement in the configure file stops the compilation

if [[ `uname` -eq Darwin ]] ; then
    compflags=" ${compflags} -isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -stdlib=libc++ "
fi

as it always equals true. The first test

This format of check works for the bash shells I have tested.

if [[ `uname` == 'Darwin' ]] ; then echo hey ;fi

**Comment by cookpa** [comment]
I can take a look later, but if you could review the script and make a PR @JustScreaming it would be great, and you can then be credited as a contributor to the project.

**Comment by JustScreaming** [comment]
@cookpa I think I've done the correct things to put in a PR. I've not do that before, first time for everything :)
